/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var user_pb = require('./user_pb.js');
var repository_pb = require('./repository_pb.js');
var deployment_pb = require('./deployment_pb.js');
goog.exportSymbol('proto.github.DeploymentStatus', null, global);
goog.exportSymbol('proto.github.DeploymentStatusEvent', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.github.DeploymentStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.github.DeploymentStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.github.DeploymentStatus.displayName = 'proto.github.DeploymentStatus';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.github.DeploymentStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.github.DeploymentStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.github.DeploymentStatus} msg The msg instance to transform.
 * @return {!Object}
 */
proto.github.DeploymentStatus.toObject = function(includeInstance, msg) {
  var f, obj = {
    url: jspb.Message.getFieldWithDefault(msg, 1, ""),
    id: jspb.Message.getFieldWithDefault(msg, 2, 0),
    state: jspb.Message.getFieldWithDefault(msg, 3, ""),
    creator: (f = msg.getCreator()) && user_pb.User.toObject(includeInstance, f),
    description: jspb.Message.getFieldWithDefault(msg, 5, ""),
    targetUrl: jspb.Message.getFieldWithDefault(msg, 6, ""),
    createdAt: jspb.Message.getFieldWithDefault(msg, 7, ""),
    updatedAt: jspb.Message.getFieldWithDefault(msg, 8, ""),
    deploymentUrl: jspb.Message.getFieldWithDefault(msg, 9, ""),
    repositoryUrl: jspb.Message.getFieldWithDefault(msg, 10, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.github.DeploymentStatus}
 */
proto.github.DeploymentStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.github.DeploymentStatus;
  return proto.github.DeploymentStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.github.DeploymentStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.github.DeploymentStatus}
 */
proto.github.DeploymentStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setState(value);
      break;
    case 4:
      var value = new user_pb.User;
      reader.readMessage(value,user_pb.User.deserializeBinaryFromReader);
      msg.setCreator(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setTargetUrl(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreatedAt(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setUpdatedAt(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeploymentUrl(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setRepositoryUrl(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.github.DeploymentStatus} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.github.DeploymentStatus.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.github.DeploymentStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.github.DeploymentStatus.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getUrl();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getId();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = this.getState();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = this.getCreator();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      user_pb.User.serializeBinaryToWriter
    );
  }
  f = this.getDescription();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = this.getTargetUrl();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = this.getCreatedAt();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = this.getUpdatedAt();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = this.getDeploymentUrl();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = this.getRepositoryUrl();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
};


/**
 * optional string url = 1;
 * @return {string}
 */
proto.github.DeploymentStatus.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.github.DeploymentStatus.prototype.setUrl = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional int32 id = 2;
 * @return {number}
 */
proto.github.DeploymentStatus.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.github.DeploymentStatus.prototype.setId = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string state = 3;
 * @return {string}
 */
proto.github.DeploymentStatus.prototype.getState = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.github.DeploymentStatus.prototype.setState = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional User creator = 4;
 * @return {?proto.github.User}
 */
proto.github.DeploymentStatus.prototype.getCreator = function() {
  return /** @type{?proto.github.User} */ (
    jspb.Message.getWrapperField(this, user_pb.User, 4));
};


/** @param {?proto.github.User|undefined} value */
proto.github.DeploymentStatus.prototype.setCreator = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.github.DeploymentStatus.prototype.clearCreator = function() {
  this.setCreator(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.github.DeploymentStatus.prototype.hasCreator = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string description = 5;
 * @return {string}
 */
proto.github.DeploymentStatus.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.github.DeploymentStatus.prototype.setDescription = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional string target_url = 6;
 * @return {string}
 */
proto.github.DeploymentStatus.prototype.getTargetUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.github.DeploymentStatus.prototype.setTargetUrl = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional string created_at = 7;
 * @return {string}
 */
proto.github.DeploymentStatus.prototype.getCreatedAt = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.github.DeploymentStatus.prototype.setCreatedAt = function(value) {
  jspb.Message.setField(this, 7, value);
};


/**
 * optional string updated_at = 8;
 * @return {string}
 */
proto.github.DeploymentStatus.prototype.getUpdatedAt = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.github.DeploymentStatus.prototype.setUpdatedAt = function(value) {
  jspb.Message.setField(this, 8, value);
};


/**
 * optional string deployment_url = 9;
 * @return {string}
 */
proto.github.DeploymentStatus.prototype.getDeploymentUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/** @param {string} value */
proto.github.DeploymentStatus.prototype.setDeploymentUrl = function(value) {
  jspb.Message.setField(this, 9, value);
};


/**
 * optional string repository_url = 10;
 * @return {string}
 */
proto.github.DeploymentStatus.prototype.getRepositoryUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/** @param {string} value */
proto.github.DeploymentStatus.prototype.setRepositoryUrl = function(value) {
  jspb.Message.setField(this, 10, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.github.DeploymentStatusEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.github.DeploymentStatusEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.github.DeploymentStatusEvent.displayName = 'proto.github.DeploymentStatusEvent';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.github.DeploymentStatusEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.github.DeploymentStatusEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.github.DeploymentStatusEvent} msg The msg instance to transform.
 * @return {!Object}
 */
proto.github.DeploymentStatusEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    deploymentStatus: (f = msg.getDeploymentStatus()) && proto.github.DeploymentStatus.toObject(includeInstance, f),
    deployment: (f = msg.getDeployment()) && deployment_pb.Deployment.toObject(includeInstance, f),
    repository: (f = msg.getRepository()) && repository_pb.Repository.toObject(includeInstance, f),
    sender: (f = msg.getSender()) && user_pb.User.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.github.DeploymentStatusEvent}
 */
proto.github.DeploymentStatusEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.github.DeploymentStatusEvent;
  return proto.github.DeploymentStatusEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.github.DeploymentStatusEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.github.DeploymentStatusEvent}
 */
proto.github.DeploymentStatusEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.github.DeploymentStatus;
      reader.readMessage(value,proto.github.DeploymentStatus.deserializeBinaryFromReader);
      msg.setDeploymentStatus(value);
      break;
    case 2:
      var value = new deployment_pb.Deployment;
      reader.readMessage(value,deployment_pb.Deployment.deserializeBinaryFromReader);
      msg.setDeployment(value);
      break;
    case 3:
      var value = new repository_pb.Repository;
      reader.readMessage(value,repository_pb.Repository.deserializeBinaryFromReader);
      msg.setRepository(value);
      break;
    case 4:
      var value = new user_pb.User;
      reader.readMessage(value,user_pb.User.deserializeBinaryFromReader);
      msg.setSender(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.github.DeploymentStatusEvent} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.github.DeploymentStatusEvent.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.github.DeploymentStatusEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.github.DeploymentStatusEvent.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getDeploymentStatus();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.github.DeploymentStatus.serializeBinaryToWriter
    );
  }
  f = this.getDeployment();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      deployment_pb.Deployment.serializeBinaryToWriter
    );
  }
  f = this.getRepository();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      repository_pb.Repository.serializeBinaryToWriter
    );
  }
  f = this.getSender();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      user_pb.User.serializeBinaryToWriter
    );
  }
};


/**
 * optional DeploymentStatus deployment_status = 1;
 * @return {?proto.github.DeploymentStatus}
 */
proto.github.DeploymentStatusEvent.prototype.getDeploymentStatus = function() {
  return /** @type{?proto.github.DeploymentStatus} */ (
    jspb.Message.getWrapperField(this, proto.github.DeploymentStatus, 1));
};


/** @param {?proto.github.DeploymentStatus|undefined} value */
proto.github.DeploymentStatusEvent.prototype.setDeploymentStatus = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.github.DeploymentStatusEvent.prototype.clearDeploymentStatus = function() {
  this.setDeploymentStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.github.DeploymentStatusEvent.prototype.hasDeploymentStatus = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Deployment deployment = 2;
 * @return {?proto.github.Deployment}
 */
proto.github.DeploymentStatusEvent.prototype.getDeployment = function() {
  return /** @type{?proto.github.Deployment} */ (
    jspb.Message.getWrapperField(this, deployment_pb.Deployment, 2));
};


/** @param {?proto.github.Deployment|undefined} value */
proto.github.DeploymentStatusEvent.prototype.setDeployment = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.github.DeploymentStatusEvent.prototype.clearDeployment = function() {
  this.setDeployment(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.github.DeploymentStatusEvent.prototype.hasDeployment = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Repository repository = 3;
 * @return {?proto.github.Repository}
 */
proto.github.DeploymentStatusEvent.prototype.getRepository = function() {
  return /** @type{?proto.github.Repository} */ (
    jspb.Message.getWrapperField(this, repository_pb.Repository, 3));
};


/** @param {?proto.github.Repository|undefined} value */
proto.github.DeploymentStatusEvent.prototype.setRepository = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.github.DeploymentStatusEvent.prototype.clearRepository = function() {
  this.setRepository(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.github.DeploymentStatusEvent.prototype.hasRepository = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional User sender = 4;
 * @return {?proto.github.User}
 */
proto.github.DeploymentStatusEvent.prototype.getSender = function() {
  return /** @type{?proto.github.User} */ (
    jspb.Message.getWrapperField(this, user_pb.User, 4));
};


/** @param {?proto.github.User|undefined} value */
proto.github.DeploymentStatusEvent.prototype.setSender = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.github.DeploymentStatusEvent.prototype.clearSender = function() {
  this.setSender(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.github.DeploymentStatusEvent.prototype.hasSender = function() {
  return jspb.Message.getField(this, 4) != null;
};


goog.object.extend(exports, proto.github);
