/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.github.ForkApplyEvent', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.github.ForkApplyEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.github.ForkApplyEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.github.ForkApplyEvent.displayName = 'proto.github.ForkApplyEvent';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.github.ForkApplyEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.github.ForkApplyEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.github.ForkApplyEvent} msg The msg instance to transform.
 * @return {!Object}
 */
proto.github.ForkApplyEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    head: jspb.Message.getFieldWithDefault(msg, 1, ""),
    header: jspb.Message.getFieldWithDefault(msg, 2, ""),
    after: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.github.ForkApplyEvent}
 */
proto.github.ForkApplyEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.github.ForkApplyEvent;
  return proto.github.ForkApplyEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.github.ForkApplyEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.github.ForkApplyEvent}
 */
proto.github.ForkApplyEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setHead(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setHeader(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setAfter(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.github.ForkApplyEvent} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.github.ForkApplyEvent.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.github.ForkApplyEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.github.ForkApplyEvent.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getHead();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getHeader();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getAfter();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string head = 1;
 * @return {string}
 */
proto.github.ForkApplyEvent.prototype.getHead = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.github.ForkApplyEvent.prototype.setHead = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string header = 2;
 * @return {string}
 */
proto.github.ForkApplyEvent.prototype.getHeader = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.github.ForkApplyEvent.prototype.setHeader = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string after = 3;
 * @return {string}
 */
proto.github.ForkApplyEvent.prototype.getAfter = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.github.ForkApplyEvent.prototype.setAfter = function(value) {
  jspb.Message.setField(this, 3, value);
};


goog.object.extend(exports, proto.github);


// patched by github-protobuf to add toJSON and fromJSON methods

function _toBool (obj) {
	if (typeof(obj) === 'boolean') { return obj; }
	if (typeof(obj) === 'string') { return obj === 'true'; }
	if (typeof(obj) === 'number') { return obj > 0; }
	return false;
};



// .github.ForkApplyEvent
proto.github.ForkApplyEvent.prototype.fromJSON = function(obj) {
	'head' in obj && this.setHead(obj.head);
	'header' in obj && this.setHeader(obj.header);
	'after' in obj && this.setAfter(obj.after);
	return this;
};

proto.github.ForkApplyEvent.prototype.toJSON = function() {
	var obj = this.toObject();
	if ('head' in obj) {
		obj.head = obj.head;
		delete obj.head;
	}
	if ('header' in obj) {
		obj.header = obj.header;
		delete obj.header;
	}
	if ('after' in obj) {
		obj.after = obj.after;
		delete obj.after;
	}
	return obj;
};

