/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var user_pb = require('./user_pb.js');
var issue_pb = require('./issue_pb.js');
var comment_pb = require('./comment_pb.js');
var repository_pb = require('./repository_pb.js');
goog.exportSymbol('proto.github.IssueCommentEvent', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.github.IssueCommentEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.github.IssueCommentEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.github.IssueCommentEvent.displayName = 'proto.github.IssueCommentEvent';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.github.IssueCommentEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.github.IssueCommentEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.github.IssueCommentEvent} msg The msg instance to transform.
 * @return {!Object}
 */
proto.github.IssueCommentEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    action: jspb.Message.getFieldWithDefault(msg, 1, ""),
    issue: (f = msg.getIssue()) && issue_pb.Issue.toObject(includeInstance, f),
    comment: (f = msg.getComment()) && comment_pb.Comment.toObject(includeInstance, f),
    repository: (f = msg.getRepository()) && repository_pb.Repository.toObject(includeInstance, f),
    sender: (f = msg.getSender()) && user_pb.User.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.github.IssueCommentEvent}
 */
proto.github.IssueCommentEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.github.IssueCommentEvent;
  return proto.github.IssueCommentEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.github.IssueCommentEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.github.IssueCommentEvent}
 */
proto.github.IssueCommentEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAction(value);
      break;
    case 2:
      var value = new issue_pb.Issue;
      reader.readMessage(value,issue_pb.Issue.deserializeBinaryFromReader);
      msg.setIssue(value);
      break;
    case 3:
      var value = new comment_pb.Comment;
      reader.readMessage(value,comment_pb.Comment.deserializeBinaryFromReader);
      msg.setComment(value);
      break;
    case 4:
      var value = new repository_pb.Repository;
      reader.readMessage(value,repository_pb.Repository.deserializeBinaryFromReader);
      msg.setRepository(value);
      break;
    case 5:
      var value = new user_pb.User;
      reader.readMessage(value,user_pb.User.deserializeBinaryFromReader);
      msg.setSender(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.github.IssueCommentEvent} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.github.IssueCommentEvent.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.github.IssueCommentEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.github.IssueCommentEvent.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getAction();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getIssue();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      issue_pb.Issue.serializeBinaryToWriter
    );
  }
  f = this.getComment();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      comment_pb.Comment.serializeBinaryToWriter
    );
  }
  f = this.getRepository();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      repository_pb.Repository.serializeBinaryToWriter
    );
  }
  f = this.getSender();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      user_pb.User.serializeBinaryToWriter
    );
  }
};


/**
 * optional string action = 1;
 * @return {string}
 */
proto.github.IssueCommentEvent.prototype.getAction = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.github.IssueCommentEvent.prototype.setAction = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional Issue issue = 2;
 * @return {?proto.github.Issue}
 */
proto.github.IssueCommentEvent.prototype.getIssue = function() {
  return /** @type{?proto.github.Issue} */ (
    jspb.Message.getWrapperField(this, issue_pb.Issue, 2));
};


/** @param {?proto.github.Issue|undefined} value */
proto.github.IssueCommentEvent.prototype.setIssue = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.github.IssueCommentEvent.prototype.clearIssue = function() {
  this.setIssue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.github.IssueCommentEvent.prototype.hasIssue = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Comment comment = 3;
 * @return {?proto.github.Comment}
 */
proto.github.IssueCommentEvent.prototype.getComment = function() {
  return /** @type{?proto.github.Comment} */ (
    jspb.Message.getWrapperField(this, comment_pb.Comment, 3));
};


/** @param {?proto.github.Comment|undefined} value */
proto.github.IssueCommentEvent.prototype.setComment = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.github.IssueCommentEvent.prototype.clearComment = function() {
  this.setComment(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.github.IssueCommentEvent.prototype.hasComment = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Repository repository = 4;
 * @return {?proto.github.Repository}
 */
proto.github.IssueCommentEvent.prototype.getRepository = function() {
  return /** @type{?proto.github.Repository} */ (
    jspb.Message.getWrapperField(this, repository_pb.Repository, 4));
};


/** @param {?proto.github.Repository|undefined} value */
proto.github.IssueCommentEvent.prototype.setRepository = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.github.IssueCommentEvent.prototype.clearRepository = function() {
  this.setRepository(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.github.IssueCommentEvent.prototype.hasRepository = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional User sender = 5;
 * @return {?proto.github.User}
 */
proto.github.IssueCommentEvent.prototype.getSender = function() {
  return /** @type{?proto.github.User} */ (
    jspb.Message.getWrapperField(this, user_pb.User, 5));
};


/** @param {?proto.github.User|undefined} value */
proto.github.IssueCommentEvent.prototype.setSender = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.github.IssueCommentEvent.prototype.clearSender = function() {
  this.setSender(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.github.IssueCommentEvent.prototype.hasSender = function() {
  return jspb.Message.getField(this, 5) != null;
};


goog.object.extend(exports, proto.github);
