/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var user_pb = require('./user_pb.js');
var repository_pb = require('./repository_pb.js');
var pull_request_pb = require('./pull_request_pb.js');
goog.exportSymbol('proto.github.PullRequestReview', null, global);
goog.exportSymbol('proto.github.PullRequestReviewEvent', null, global);
goog.exportSymbol('proto.github.PullRequestReviewLink', null, global);
goog.exportSymbol('proto.github.PullRequestReviewLinks', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.github.PullRequestReviewLink = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.github.PullRequestReviewLink, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.github.PullRequestReviewLink.displayName = 'proto.github.PullRequestReviewLink';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.github.PullRequestReviewLink.prototype.toObject = function(opt_includeInstance) {
  return proto.github.PullRequestReviewLink.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.github.PullRequestReviewLink} msg The msg instance to transform.
 * @return {!Object}
 */
proto.github.PullRequestReviewLink.toObject = function(includeInstance, msg) {
  var f, obj = {
    html: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.github.PullRequestReviewLink}
 */
proto.github.PullRequestReviewLink.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.github.PullRequestReviewLink;
  return proto.github.PullRequestReviewLink.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.github.PullRequestReviewLink} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.github.PullRequestReviewLink}
 */
proto.github.PullRequestReviewLink.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setHtml(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.github.PullRequestReviewLink} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.github.PullRequestReviewLink.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.github.PullRequestReviewLink.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.github.PullRequestReviewLink.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getHtml();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string html = 1;
 * @return {string}
 */
proto.github.PullRequestReviewLink.prototype.getHtml = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.github.PullRequestReviewLink.prototype.setHtml = function(value) {
  jspb.Message.setField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.github.PullRequestReviewLinks = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.github.PullRequestReviewLinks, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.github.PullRequestReviewLinks.displayName = 'proto.github.PullRequestReviewLinks';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.github.PullRequestReviewLinks.prototype.toObject = function(opt_includeInstance) {
  return proto.github.PullRequestReviewLinks.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.github.PullRequestReviewLinks} msg The msg instance to transform.
 * @return {!Object}
 */
proto.github.PullRequestReviewLinks.toObject = function(includeInstance, msg) {
  var f, obj = {
    html: (f = msg.getHtml()) && proto.github.PullRequestReviewLink.toObject(includeInstance, f),
    pullRequest: (f = msg.getPullRequest()) && proto.github.PullRequestReviewLink.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.github.PullRequestReviewLinks}
 */
proto.github.PullRequestReviewLinks.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.github.PullRequestReviewLinks;
  return proto.github.PullRequestReviewLinks.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.github.PullRequestReviewLinks} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.github.PullRequestReviewLinks}
 */
proto.github.PullRequestReviewLinks.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.github.PullRequestReviewLink;
      reader.readMessage(value,proto.github.PullRequestReviewLink.deserializeBinaryFromReader);
      msg.setHtml(value);
      break;
    case 2:
      var value = new proto.github.PullRequestReviewLink;
      reader.readMessage(value,proto.github.PullRequestReviewLink.deserializeBinaryFromReader);
      msg.setPullRequest(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.github.PullRequestReviewLinks} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.github.PullRequestReviewLinks.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.github.PullRequestReviewLinks.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.github.PullRequestReviewLinks.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getHtml();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.github.PullRequestReviewLink.serializeBinaryToWriter
    );
  }
  f = this.getPullRequest();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.github.PullRequestReviewLink.serializeBinaryToWriter
    );
  }
};


/**
 * optional PullRequestReviewLink html = 1;
 * @return {?proto.github.PullRequestReviewLink}
 */
proto.github.PullRequestReviewLinks.prototype.getHtml = function() {
  return /** @type{?proto.github.PullRequestReviewLink} */ (
    jspb.Message.getWrapperField(this, proto.github.PullRequestReviewLink, 1));
};


/** @param {?proto.github.PullRequestReviewLink|undefined} value */
proto.github.PullRequestReviewLinks.prototype.setHtml = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.github.PullRequestReviewLinks.prototype.clearHtml = function() {
  this.setHtml(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.github.PullRequestReviewLinks.prototype.hasHtml = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional PullRequestReviewLink pull_request = 2;
 * @return {?proto.github.PullRequestReviewLink}
 */
proto.github.PullRequestReviewLinks.prototype.getPullRequest = function() {
  return /** @type{?proto.github.PullRequestReviewLink} */ (
    jspb.Message.getWrapperField(this, proto.github.PullRequestReviewLink, 2));
};


/** @param {?proto.github.PullRequestReviewLink|undefined} value */
proto.github.PullRequestReviewLinks.prototype.setPullRequest = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.github.PullRequestReviewLinks.prototype.clearPullRequest = function() {
  this.setPullRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.github.PullRequestReviewLinks.prototype.hasPullRequest = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.github.PullRequestReview = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.github.PullRequestReview, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.github.PullRequestReview.displayName = 'proto.github.PullRequestReview';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.github.PullRequestReview.prototype.toObject = function(opt_includeInstance) {
  return proto.github.PullRequestReview.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.github.PullRequestReview} msg The msg instance to transform.
 * @return {!Object}
 */
proto.github.PullRequestReview.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    user: (f = msg.getUser()) && user_pb.User.toObject(includeInstance, f),
    body: jspb.Message.getFieldWithDefault(msg, 3, ""),
    submittedAt: jspb.Message.getFieldWithDefault(msg, 4, ""),
    state: jspb.Message.getFieldWithDefault(msg, 5, ""),
    htmlUrl: jspb.Message.getFieldWithDefault(msg, 6, ""),
    pullRequestUrl: jspb.Message.getFieldWithDefault(msg, 7, ""),
    links: (f = msg.getLinks()) && proto.github.PullRequestReviewLinks.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.github.PullRequestReview}
 */
proto.github.PullRequestReview.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.github.PullRequestReview;
  return proto.github.PullRequestReview.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.github.PullRequestReview} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.github.PullRequestReview}
 */
proto.github.PullRequestReview.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = new user_pb.User;
      reader.readMessage(value,user_pb.User.deserializeBinaryFromReader);
      msg.setUser(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setBody(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubmittedAt(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setState(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setHtmlUrl(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setPullRequestUrl(value);
      break;
    case 8:
      var value = new proto.github.PullRequestReviewLinks;
      reader.readMessage(value,proto.github.PullRequestReviewLinks.deserializeBinaryFromReader);
      msg.setLinks(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.github.PullRequestReview} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.github.PullRequestReview.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.github.PullRequestReview.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.github.PullRequestReview.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = this.getUser();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      user_pb.User.serializeBinaryToWriter
    );
  }
  f = this.getBody();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = this.getSubmittedAt();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = this.getState();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = this.getHtmlUrl();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = this.getPullRequestUrl();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = this.getLinks();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.github.PullRequestReviewLinks.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.github.PullRequestReview.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.github.PullRequestReview.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional User user = 2;
 * @return {?proto.github.User}
 */
proto.github.PullRequestReview.prototype.getUser = function() {
  return /** @type{?proto.github.User} */ (
    jspb.Message.getWrapperField(this, user_pb.User, 2));
};


/** @param {?proto.github.User|undefined} value */
proto.github.PullRequestReview.prototype.setUser = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.github.PullRequestReview.prototype.clearUser = function() {
  this.setUser(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.github.PullRequestReview.prototype.hasUser = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string body = 3;
 * @return {string}
 */
proto.github.PullRequestReview.prototype.getBody = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.github.PullRequestReview.prototype.setBody = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string submitted_at = 4;
 * @return {string}
 */
proto.github.PullRequestReview.prototype.getSubmittedAt = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.github.PullRequestReview.prototype.setSubmittedAt = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string state = 5;
 * @return {string}
 */
proto.github.PullRequestReview.prototype.getState = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.github.PullRequestReview.prototype.setState = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional string html_url = 6;
 * @return {string}
 */
proto.github.PullRequestReview.prototype.getHtmlUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.github.PullRequestReview.prototype.setHtmlUrl = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional string pull_request_url = 7;
 * @return {string}
 */
proto.github.PullRequestReview.prototype.getPullRequestUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.github.PullRequestReview.prototype.setPullRequestUrl = function(value) {
  jspb.Message.setField(this, 7, value);
};


/**
 * optional PullRequestReviewLinks _links = 8;
 * @return {?proto.github.PullRequestReviewLinks}
 */
proto.github.PullRequestReview.prototype.getLinks = function() {
  return /** @type{?proto.github.PullRequestReviewLinks} */ (
    jspb.Message.getWrapperField(this, proto.github.PullRequestReviewLinks, 8));
};


/** @param {?proto.github.PullRequestReviewLinks|undefined} value */
proto.github.PullRequestReview.prototype.setLinks = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


proto.github.PullRequestReview.prototype.clearLinks = function() {
  this.setLinks(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.github.PullRequestReview.prototype.hasLinks = function() {
  return jspb.Message.getField(this, 8) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.github.PullRequestReviewEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.github.PullRequestReviewEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.github.PullRequestReviewEvent.displayName = 'proto.github.PullRequestReviewEvent';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.github.PullRequestReviewEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.github.PullRequestReviewEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.github.PullRequestReviewEvent} msg The msg instance to transform.
 * @return {!Object}
 */
proto.github.PullRequestReviewEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    action: jspb.Message.getFieldWithDefault(msg, 1, ""),
    review: (f = msg.getReview()) && proto.github.PullRequestReview.toObject(includeInstance, f),
    pullRequest: (f = msg.getPullRequest()) && pull_request_pb.PullRequest.toObject(includeInstance, f),
    repository: (f = msg.getRepository()) && repository_pb.Repository.toObject(includeInstance, f),
    sender: (f = msg.getSender()) && user_pb.User.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.github.PullRequestReviewEvent}
 */
proto.github.PullRequestReviewEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.github.PullRequestReviewEvent;
  return proto.github.PullRequestReviewEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.github.PullRequestReviewEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.github.PullRequestReviewEvent}
 */
proto.github.PullRequestReviewEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAction(value);
      break;
    case 2:
      var value = new proto.github.PullRequestReview;
      reader.readMessage(value,proto.github.PullRequestReview.deserializeBinaryFromReader);
      msg.setReview(value);
      break;
    case 3:
      var value = new pull_request_pb.PullRequest;
      reader.readMessage(value,pull_request_pb.PullRequest.deserializeBinaryFromReader);
      msg.setPullRequest(value);
      break;
    case 4:
      var value = new repository_pb.Repository;
      reader.readMessage(value,repository_pb.Repository.deserializeBinaryFromReader);
      msg.setRepository(value);
      break;
    case 5:
      var value = new user_pb.User;
      reader.readMessage(value,user_pb.User.deserializeBinaryFromReader);
      msg.setSender(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.github.PullRequestReviewEvent} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.github.PullRequestReviewEvent.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.github.PullRequestReviewEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.github.PullRequestReviewEvent.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getAction();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getReview();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.github.PullRequestReview.serializeBinaryToWriter
    );
  }
  f = this.getPullRequest();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      pull_request_pb.PullRequest.serializeBinaryToWriter
    );
  }
  f = this.getRepository();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      repository_pb.Repository.serializeBinaryToWriter
    );
  }
  f = this.getSender();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      user_pb.User.serializeBinaryToWriter
    );
  }
};


/**
 * optional string action = 1;
 * @return {string}
 */
proto.github.PullRequestReviewEvent.prototype.getAction = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.github.PullRequestReviewEvent.prototype.setAction = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional PullRequestReview review = 2;
 * @return {?proto.github.PullRequestReview}
 */
proto.github.PullRequestReviewEvent.prototype.getReview = function() {
  return /** @type{?proto.github.PullRequestReview} */ (
    jspb.Message.getWrapperField(this, proto.github.PullRequestReview, 2));
};


/** @param {?proto.github.PullRequestReview|undefined} value */
proto.github.PullRequestReviewEvent.prototype.setReview = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.github.PullRequestReviewEvent.prototype.clearReview = function() {
  this.setReview(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.github.PullRequestReviewEvent.prototype.hasReview = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional PullRequest pull_request = 3;
 * @return {?proto.github.PullRequest}
 */
proto.github.PullRequestReviewEvent.prototype.getPullRequest = function() {
  return /** @type{?proto.github.PullRequest} */ (
    jspb.Message.getWrapperField(this, pull_request_pb.PullRequest, 3));
};


/** @param {?proto.github.PullRequest|undefined} value */
proto.github.PullRequestReviewEvent.prototype.setPullRequest = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.github.PullRequestReviewEvent.prototype.clearPullRequest = function() {
  this.setPullRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.github.PullRequestReviewEvent.prototype.hasPullRequest = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Repository repository = 4;
 * @return {?proto.github.Repository}
 */
proto.github.PullRequestReviewEvent.prototype.getRepository = function() {
  return /** @type{?proto.github.Repository} */ (
    jspb.Message.getWrapperField(this, repository_pb.Repository, 4));
};


/** @param {?proto.github.Repository|undefined} value */
proto.github.PullRequestReviewEvent.prototype.setRepository = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.github.PullRequestReviewEvent.prototype.clearRepository = function() {
  this.setRepository(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.github.PullRequestReviewEvent.prototype.hasRepository = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional User sender = 5;
 * @return {?proto.github.User}
 */
proto.github.PullRequestReviewEvent.prototype.getSender = function() {
  return /** @type{?proto.github.User} */ (
    jspb.Message.getWrapperField(this, user_pb.User, 5));
};


/** @param {?proto.github.User|undefined} value */
proto.github.PullRequestReviewEvent.prototype.setSender = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.github.PullRequestReviewEvent.prototype.clearSender = function() {
  this.setSender(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.github.PullRequestReviewEvent.prototype.hasSender = function() {
  return jspb.Message.getField(this, 5) != null;
};


goog.object.extend(exports, proto.github);


// patched by github-protobuf to add toJSON and fromJSON methods

function _toBool (obj) {
	if (typeof(obj) === 'boolean') { return obj; }
	if (typeof(obj) === 'string') { return obj === 'true'; }
	if (typeof(obj) === 'number') { return obj > 0; }
	return false;
};



// .github.PullRequestReviewLinks
proto.github.PullRequestReviewLinks.prototype.fromJSON = function(obj) {
	if ('html' in obj) {
		var PullRequestReviewLink = require('./pull_request_review_event_pb.js').PullRequestReviewLink;
		var PullRequestReviewLinkInstance = new PullRequestReviewLink();
		this.setHtml(PullRequestReviewLinkInstance.fromJSON(obj.html));
	}
	if ('pull_request' in obj) {
		var PullRequestReviewLink = require('./pull_request_review_event_pb.js').PullRequestReviewLink;
		var PullRequestReviewLinkInstance = new PullRequestReviewLink();
		this.setPullRequest(PullRequestReviewLinkInstance.fromJSON(obj.pull_request));
	}
	return this;
};

proto.github.PullRequestReviewLinks.prototype.toJSON = function() {
	var obj = this.toObject();
	if ('html' in obj) {
		obj.html = this.getHtml().toJSON();
	}
	if ('pullRequest' in obj) {
		obj.pull_request = this.getPullRequest().toJSON();
	}
	return obj;
};



// .github.PullRequestReview
proto.github.PullRequestReview.prototype.fromJSON = function(obj) {
	'id' in obj && this.setId(+obj.id);
	if ('user' in obj) {
		var User = require('./user_pb.js').User;
		var UserInstance = new User();
		this.setUser(UserInstance.fromJSON(obj.user));
	}
	'body' in obj && this.setBody(obj.body);
	'submitted_at' in obj && this.setSubmittedAt(obj.submitted_at);
	'state' in obj && this.setState(obj.state);
	'html_url' in obj && this.setHtmlUrl(obj.html_url);
	'pull_request_url' in obj && this.setPullRequestUrl(obj.pull_request_url);
	if ('_links' in obj) {
		var PullRequestReviewLinks = require('./pull_request_review_event_pb.js').PullRequestReviewLinks;
		var PullRequestReviewLinksInstance = new PullRequestReviewLinks();
		this.setLinks(PullRequestReviewLinksInstance.fromJSON(obj._links));
	}
	return this;
};

proto.github.PullRequestReview.prototype.toJSON = function() {
	var obj = this.toObject();
	if ('id' in obj) {
		obj.id = obj.id;
		delete obj.id;
	}
	if ('user' in obj) {
		obj.user = this.getUser().toJSON();
	}
	if ('body' in obj) {
		obj.body = obj.body;
		delete obj.body;
	}
	if ('submittedAt' in obj) {
		obj.submitted_at = obj.submittedAt;
		delete obj.submittedAt;
	}
	if ('state' in obj) {
		obj.state = obj.state;
		delete obj.state;
	}
	if ('htmlUrl' in obj) {
		obj.html_url = obj.htmlUrl;
		delete obj.htmlUrl;
	}
	if ('pullRequestUrl' in obj) {
		obj.pull_request_url = obj.pullRequestUrl;
		delete obj.pullRequestUrl;
	}
	if ('Links' in obj) {
		obj._links = this.getLinks().toJSON();
	}
	return obj;
};



// .github.PullRequestReviewLink
proto.github.PullRequestReviewLink.prototype.fromJSON = function(obj) {
	'html' in obj && this.setHtml(obj.html);
	return this;
};

proto.github.PullRequestReviewLink.prototype.toJSON = function() {
	var obj = this.toObject();
	if ('html' in obj) {
		obj.html = obj.html;
		delete obj.html;
	}
	return obj;
};



// .github.PullRequestReviewEvent
proto.github.PullRequestReviewEvent.prototype.fromJSON = function(obj) {
	'action' in obj && this.setAction(obj.action);
	if ('review' in obj) {
		var PullRequestReview = require('./pull_request_review_event_pb.js').PullRequestReview;
		var PullRequestReviewInstance = new PullRequestReview();
		this.setReview(PullRequestReviewInstance.fromJSON(obj.review));
	}
	if ('pull_request' in obj) {
		var PullRequest = require('./pull_request_pb.js').PullRequest;
		var PullRequestInstance = new PullRequest();
		this.setPullRequest(PullRequestInstance.fromJSON(obj.pull_request));
	}
	if ('repository' in obj) {
		var Repository = require('./repository_pb.js').Repository;
		var RepositoryInstance = new Repository();
		this.setRepository(RepositoryInstance.fromJSON(obj.repository));
	}
	if ('sender' in obj) {
		var User = require('./user_pb.js').User;
		var UserInstance = new User();
		this.setSender(UserInstance.fromJSON(obj.sender));
	}
	return this;
};

proto.github.PullRequestReviewEvent.prototype.toJSON = function() {
	var obj = this.toObject();
	if ('action' in obj) {
		obj.action = obj.action;
		delete obj.action;
	}
	if ('review' in obj) {
		obj.review = this.getReview().toJSON();
	}
	if ('pullRequest' in obj) {
		obj.pull_request = this.getPullRequest().toJSON();
	}
	if ('repository' in obj) {
		obj.repository = this.getRepository().toJSON();
	}
	if ('sender' in obj) {
		obj.sender = this.getSender().toJSON();
	}
	return obj;
};

